#!/usr/bin/env bash
set -e

cd ~/.vim

echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim/my_configs.vim
set runtimepath+=~/.vim
source ~/.vim/vimrcs/basic.vim
source ~/.vim/vimrcs/plugins.vim
source ~/.vim/vimrcs/extended.vim
source ~/.vim/my_configs.vim
' > ~/.vimrc

echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"
